'use client';

import { useState } from 'react';
import type { BriefResponse } from '@/lib/brief';
import { Skeleton } from './ui';

const REASON_COPY: Record<string, string> = {
  'no-key': 'No OpenAI key is configured on this deployment, so this is the rule-based brief.',
  timeout: 'The model did not respond in time, so this is the rule-based brief.',
  'rate-limited': 'The API is rate limited right now, so this is the rule-based brief.',
  error: 'The model call failed, so this is the rule-based brief.',
  'empty-response': 'The model returned nothing usable, so this is the rule-based brief.',
};

export default function AiBrief({ customerId }: { customerId: string }) {
  const [state, setState] = useState<'idle' | 'loading' | 'done' | 'error'>('idle');
  const [brief, setBrief] = useState<BriefResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const run = async () => {
    setState('loading');
    setError(null);
    try {
      const res = await fetch('/api/brief', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ customerId }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body?.error ?? `Request failed with status ${res.status}.`);
      }
      setBrief(await res.json());
      setState('done');
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Unexpected error.');
      setState('error');
    }
  };

  if (state === 'idle') {
    return (
      <div className="flex flex-col gap-2.5">
        <p className="text-[12px] leading-relaxed text-muted">
          Reads the free-text account note against the computed signals and tells you what to understand
          before making contact. It cannot change the score or the ranking — those are already fixed above.
        </p>
        <button
          onClick={run}
          className="self-start rounded bg-accent px-3 py-1.5 text-[12px] font-medium text-white transition-opacity hover:opacity-90"
        >
          Generate brief
        </button>
      </div>
    );
  }

  if (state === 'loading') {
    return (
      <div className="flex flex-col gap-2" aria-busy="true" aria-live="polite">
        <span className="sr-only">Generating the account brief</span>
        <Skeleton className="h-4 w-3/4" />
        <Skeleton className="h-3 w-full" />
        <Skeleton className="h-3 w-full" />
        <Skeleton className="h-3 w-2/3" />
      </div>
    );
  }

  if (state === 'error') {
    return (
      <div role="alert" className="flex flex-col gap-2">
        <p className="text-[12px] text-risk-critical">{error}</p>
        <button
          onClick={run}
          className="self-start rounded border border-border-subtle px-2.5 py-1 text-[12px] hover:border-border-strong"
        >
          Try again
        </button>
      </div>
    );
  }

  if (!brief) return null;

  return (
    <div className="flex flex-col gap-3">
      <p className="text-[13px] font-medium leading-snug">{brief.headline}</p>
      {brief.reading && <p className="text-[12px] leading-relaxed text-muted">{brief.reading}</p>}

      {brief.noteRiskPresent && brief.noteRiskSummary && (
        <div className="rounded border border-risk-elevated/30 bg-risk-elevated-bg px-3 py-2.5">
          <p className="text-[11px] font-semibold uppercase tracking-wide text-risk-elevated">
            In the note, not in the score
          </p>
          <p className="mt-1 text-[12px] leading-relaxed">{brief.noteRiskSummary}</p>
          <p className="mt-1.5 text-[11px] leading-relaxed text-muted">
            Advisory only. This does not move the risk score or the ranking — a number that cannot be
            reproduced should not reorder a work queue.
          </p>
        </div>
      )}

      {brief.openingLine && (
        <div className="rounded border border-border-subtle bg-surface-2 px-3 py-2.5">
          <p className="text-[11px] uppercase tracking-wide text-muted-2">Suggested opening</p>
          <p className="mt-1 text-[12px] leading-relaxed">{brief.openingLine}</p>
        </div>
      )}

      <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-muted-2">
        {brief.source === 'llm' ? (
          <span>
            Generated by {brief.model}
            {brief.cached ? ' · cached' : ''}
          </span>
        ) : (
          <span>{REASON_COPY[brief.fallbackReason ?? 'error'] ?? 'Rule-based brief.'}</span>
        )}
        <button onClick={run} className="text-accent hover:underline">
          Regenerate
        </button>
      </div>
    </div>
  );
}
